version: '2.1'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888
      - 7891:7891

  registry:
    build: registry

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 5000:5000

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  account-service:
    build: account-service
    ports:
      - 6000:6000
      - 7892:7892

  account-mongodb:
    build: mongodb
    ports:
      - 26000:27017

  admin-service:
    build: admin-service
    ports:
      - 9999:9999
      - 7890:7890

  admin-mongodb:
    build: mongodb
    ports:
      - 29000:27017

  statistics-service:
    build: statistics-service
    ports:
      - 7000:7000

  statistics-mongodb:
    build: mongodb
    ports:
      - 27000:27017

  notification-service:
    build: notification-service
    ports:
      - 8000:8000

  notification-mongodb:
    build: mongodb
    ports:
      - 28000:27017

  monitoring:
    build: monitoring

  turbine-stream-service:
    build: turbine-stream-service

  zipkin:
    ports:
      - 9411:9411

  zipkin-ui:
    ports:
      - 5555:80
