security:
  oauth2:
    client:
      clientId: admin-service
      clientSecret: ${ADMIN_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: admin-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
  zipkin:
    sender:
      type: rabbit
    base-url: http://zipkin-service:9411
  sleuth:
    sampler:
      probability: 1

logging:
  level:
    root: DEBUG

server:
  servlet:
    context-path: /admin
  port: 9999

feign:
  hystrix:
    enabled: true