spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
  zipkin:
    sender:
      type: rabbit
    base-url: http://zipkin-service:9411
  sleuth:
    sampler:
      probability: 1

logging:
  level:
    root: DEBUG

server:
  servlet:
    context-path: /uaa
  port: 5000
